[build]
  command = "npm install && cd web-client && npm install && npm run build"
  publish = "web-client/.next"

# Disable secrets scanning for Firebase client API keys (safe to expose)
[build.processing]
  skip_processing = false

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"
  NEXT_PUBLIC_SUPABASE_URL = "https://pznzykwfboqryuibelqs.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6bnp5a3dmYm9xcnl1aWJlbHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNTk3MjUsImV4cCI6MjA3NDkzNTcyNX0.BIdyGbIUTzGdMSp7PI9gNiwmLgUmcD9jqBU7LHH5YIU"
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyCmm7pGnSM2FQCiIQtFBowhaXP2xHpO-6I"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "madameai.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_DATABASE_URL = "https://madameai-default-rtdb.firebaseio.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "madameai"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "madameai.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "96843253648"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:96843253648:web:ddac677180656d17e15515"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-6WL3CJKEN0"
  FIREBASE_DATABASE_URL = "https://madameai-default-rtdb.firebaseio.com"

[context.production.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://pznzykwfboqryuibelqs.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6bnp5a3dmYm9xcnl1aWJlbHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNTk3MjUsImV4cCI6MjA3NDkzNTcyNX0.BIdyGbIUTzGdMSp7PI9gNiwmLgUmcD9jqBU7LHH5YIU"
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyCmm7pGnSM2FQCiIQtFBowhaXP2xHpO-6I"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "madameai.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_DATABASE_URL = "https://madameai-default-rtdb.firebaseio.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "madameai"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "madameai.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "96843253648"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:96843253648:web:ddac677180656d17e15515"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-6WL3CJKEN0"
  FIREBASE_DATABASE_URL = "https://madameai-default-rtdb.firebaseio.com"

# Use Netlify's Next.js plugin for proper routing
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "api"
  node_bundler = "esbuild"

[functions.environment]
  SPEECHACE_API_ENDPOINT = "https://api.speechace.co"
  SPEECHACE_REGION = "us-west"
  NEXT_PUBLIC_SUPABASE_URL = "https://pznzykwfboqryuibelqs.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6bnp5a3dmYm9xcnl1aWJlbHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNTk3MjUsImV4cCI6MjA3NDkzNTcyNX0.BIdyGbIUTzGdMSp7PI9gNiwmLgUmcD9jqBU7LHH5YIU"
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyCmm7pGnSM2FQCiIQtFBowhaXP2xHpO-6I"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "madameai.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_DATABASE_URL = "https://madameai-default-rtdb.firebaseio.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "madameai"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "madameai.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "96843253648"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:96843253648:web:ddac677180656d17e15515"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-6WL3CJKEN0"
  FIREBASE_PROJECT_ID = "madameai"
  FIREBASE_CLIENT_EMAIL = "firebase-adminsdk@madameai.iam.gserviceaccount.com"
  FIREBASE_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\\nPLEASE_PROVIDE_SERVICE_ACCOUNT_PRIVATE_KEY\\n-----END PRIVATE KEY-----\\n"
  FIREBASE_DATABASE_URL = "https://madameai-default-rtdb.firebaseio.com"
  FIREBASE_STORAGE_BUCKET = "madameai.firebasestorage.app"

# IMPORTANT: Set sensitive keys in Netlify UI (Site settings > Environment variables):
# - OPENAI_API_KEY, SPEECHACE_API_KEY, ELEVENLABS_API_KEY
# - FIREBASE_PROJECT_ID, FIREBASE_CLIENT_EMAIL, FIREBASE_PRIVATE_KEY, FIREBASE_DATABASE_URL
