[build]
  command = "npm install && cd web-client && npm install && npm run build"
  publish = "web-client/.next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_PUBLIC_SUPABASE_URL = "https://pznzykwfboqryuibelqs.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6bnp5a3dmYm9xcnl1aWJlbHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNTk3MjUsImV4cCI6MjA3NDkzNTcyNX0.BIdyGbIUTzGdMSp7PI9gNiwmLgUmcD9jqBU7LHH5YIU"

[context.production.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://pznzykwfboqryuibelqs.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6bnp5a3dmYm9xcnl1aWJlbHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNTk3MjUsImV4cCI6MjA3NDkzNTcyNX0.BIdyGbIUTzGdMSp7PI9gNiwmLgUmcD9jqBU7LHH5YIU"

# Use Netlify's Next.js plugin for proper routing
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "api"
  node_bundler = "esbuild"

[functions.environment]
  SPEECHACE_API_ENDPOINT = "https://api.speechace.co"
  SPEECHACE_REGION = "us-west"
  NEXT_PUBLIC_SUPABASE_URL = "https://pznzykwfboqryuibelqs.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6bnp5a3dmYm9xcnl1aWJlbHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNTk3MjUsImV4cCI6MjA3NDkzNTcyNX0.BIdyGbIUTzGdMSp7PI9gNiwmLgUmcD9jqBU7LHH5YIU"

# IMPORTANT: Set these sensitive keys in Netlify UI (Site settings > Environment variables):
#
# Required API Keys:
# - OPENAI_API_KEY: Your OpenAI API key for AI generation
# - SPEECHACE_API_KEY: Your SpeechAce API key for pronunciation analysis
# - ELEVENLABS_API_KEY: Your ElevenLabs API key for text-to-speech
# - SUPABASE_SERVICE_ROLE_KEY: Your Supabase service role key (bypasses RLS for server operations)
#
# How to add:
# 1. Go to: https://app.netlify.com/sites/francoflex-pronunciation-ai/settings/env
# 2. Click "Add a variable"
# 3. Add each key-value pair
# 4. Redeploy the site
#
# To get SUPABASE_SERVICE_ROLE_KEY:
# 1. Go to: https://supabase.com/dashboard/project/pznzykwfboqryuibelqs/settings/api
# 2. Copy the "service_role" key (NOT the anon key)
# 3. Add to Netlify environment variables
